// import { useAppSelector } from "../../../redux/hooks";

// const loginUser = useAppSelector((state) => state.user.user);

export const reviewPost = [
  {
    _id: 'post01',
    id: 'post01',
    postDate: '2022-06-18T17:40:12.000Z',
    contentHeading: 'An incredible movie. One that lives with you..',
    content: "It is no wonder that the film has such a high rating, it is quite literally breathtaking. What can I say that hasn't said before? Not much, it's the story, the acting, the premise, but most of all, this movie is about how it makes you feel. Sometimes you watch a film, and can't remember it days later, this film loves with you, once you've seen it, you don't forget.",
    userName: 'Nathaniel Lewis',
    profileImage: 'https://i.pravatar.cc/300?img=14',
    userId: 'user01',
    likes: 12,
    likeIcon: false,
    likeCount: 12,
    commentCount: 10,
    rating: 4.5,
    goreFactor: 5.0,
    worthWatching: true,
  },
  {
    _id: 'post02',
    id: 'post02',
    postDate: '2022-06-18T17:40:12.000Z',
    contentHeading: 'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.',
    content: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
    userName: 'Aly Khan',
    profileImage: 'https://i.pravatar.cc/300?img=15',
    userId: 'user01',
    likes: 20,
    likeIcon: false,
    likeCount: 20,
    commentCount: 10,
    rating: 4.5,
    goreFactor: 5.0,
    worthWatching: false,
  },
  {
    _id: 'post03',
    id: 'post03',
    postDate: '2022-06-18T17:40:12.000Z',
    contentHeading: 'An incredible movie. One that lives with you.',
    userName: 'Nathaniel Lewis',
    profileImage: 'https://i.pravatar.cc/300?img=14',
    userId: 'user01',
    likes: 20,
    likeIcon: false,
    likeCount: 20,
    commentCount: 10,
    spoiler: true,
  },
];

export const reviewComments = [
  {
    createdAt: '2023-02-23T19:16:38.504Z',
    feedPostId: 'post01',
    images: [],
    likeCount: 24,
    likedByUser: false,
    message: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has.',
    replies: [
      {
        createdAt: '2023-02-23T19:17:08.035Z',
        feedCommentId: 'comment01',
        feedPostId: 'post01',
        images: [],
        likeCount: 24,
        likedByUser: false,
        message: '##LINK_ID##63f8a985b304e6b21f0b7d69@nency_1##LINK_END## awsed eque porro quisquam est qui dolorem ipsum',
        userId: {
          profilePic: 'http://localhost:4000/api/v1/local-storage/profile/profile_dce6e2b2-18a1-44f4-8271-ea38bf575217.jpg',
          userName: 'nency_1',
          _id: '634d06ae9787d60afbddff96',
        },
        _id: 'comment01reply01',
      },
      {
        createdAt: '2023-02-23T19:17:08.035Z',
        feedCommentId: 'comment01',
        feedPostId: 'post01',
        images: [],
        likeCount: 0,
        likedByUser: false,
        message: "##LINK_ID##63f8a985b304e6b21f0b7d69@nency_1##LINK_END## awsed Lorem Ipsum has been the industry's standard dummy",
        userId: {
          profilePic: 'http://localhost:4000/api/v1/local-storage/profile/profile_dce6e2b2-18a1-44f4-8271-ea38bf575217.jpg',
          userName: 'nency_1',
          _id: '634d06ae9787d60afbddff96',
        },
        _id: 'comment01reply02',
      },
    ],
    userId: {
      profilePic: 'http://localhost:4000/api/v1/local-storage/profile/profile_dce6e2b2-18a1-44f4-8271-ea38bf575217.jpg',
      userName: 'nency_1',
      _id: '634d06ae9787d60afbddff96',
    },
    _id: 'comment01',
  },
  {
    createdAt: '2023-02-23T19:16:38.504Z',
    feedPostId: 'post01',
    images: [],
    likeCount: 24,
    likedByUser: false,
    message: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has.',
    replies: [],
    userId: {
      profilePic: 'http://localhost:4000/api/v1/local-storage/profile/profile_dce6e2b2-18a1-44f4-8271-ea38bf575217.jpg',
      userName: 'nency_1',
      _id: '634d06ae9787d60afbddff96',
    },
    _id: 'comment02',
  },
];
