version: "3.9"

services:
  app:
    restart: on-failure
    build:
      context: ./
      dockerfile: app.Dockerfile
    env_file:
      - ./.env.development
    environment:
      # Override DB_CONNECTION_URL env value to point to "mongo" hostname
      - DB_CONNECTION_URL=mongodb://root:rootpassword@mongo:27017/slasher?authSource=admin
    ports:
      - '4000:4000'
    networks:
      - app-network
    depends_on:
      - mongo
  cron:
    restart: on-failure
    build:
      context: ./
      dockerfile: cron.Dockerfile
    env_file:
      - ./.env.development
    environment:
      # Override DB_CONNECTION_URL env value to point to "mongo" hostname
      - DB_CONNECTION_URL=mongodb://root:rootpassword@mongo:27017/slasher?authSource=admin
    ports:
      - '4001:4000'
    networks:
      - cron-network
    depends_on:
      - mongo
  mongo:
    build: ./docker/mongo
    restart: on-failure
    ports:
      - '27017:27017'
    networks:
      - app-network
      - cron-network
  redis:
    build: ./docker/redis
    restart: on-failure
    ports:
      - '6379:6379'
    networks:
      - app-network
      - cron-network
  nginx:
    build:
      context: ./docker/nginx
      args:
        NGINX_PORT: 80
        APP_HOST_NAME: app
        APP_PORT: 4000
    restart: on-failure
    ports:
      - '80:80'
    networks:
      - app-network
    depends_on:
      - app

networks:
    app-network:
    cron-network:
