# Docker compose setup for development and testing
version: "3.9"

# Although a name isn't required for docker to work, we want to explicitly specify it so we know
# which prefix is used for the volumes that we create.
name: 'slasher-devtest'

volumes:
  mongo-data:
services:
  mongo:
    build: ./docker/mongo
    restart: on-failure
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
