AWSTemplateFormatVersion: 2010-09-09
Description: EC2 development instance

# Create stack:
# aws cloudformation create-stack --stack-name slasher-dev-server \
# --template-body file://deploy/cloudformation/dev-environment.yml \
# --parameters ParameterKey=SSHLocation,ParameterValue=1.2.3.4/32

# Describe latest changes (ask AWS to describe what WILL change, but do not make any changes):
# aws cloudformation delete-change-set --stack-name slasher-dev-server --change-set-name test-change-set && \
# aws cloudformation create-change-set --stack-name slasher-dev-server --change-set-name test-change-set --change-set-type UPDATE \
# --template-body file://deploy/cloudformation/dev-environment.yml \
# --parameters ParameterKey=SSHLocation,ParameterValue=1.2.3.4/32 && \
# aws cloudformation describe-change-set --stack-name slasher-dev-server --change-set-name test-change-set

# Update stack:
# aws cloudformation update-stack --stack-name slasher-dev-server \
# --template-body file://deploy/cloudformation/dev-environment.yml \
# --parameters ParameterKey=SSHLocation,ParameterValue=1.2.3.4/32

# Delete stack:
# aws cloudformation delete-stack --stack-name slasher-dev-server

# Estimate cost for stack:
# aws cloudformation estimate-template-cost --template-body file://deploy/cloudformation/dev-environment.yml \
# --parameters ParameterKey=SSHLocation,ParameterValue=1.2.3.4/32

Parameters:
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "Must be a valid IP CIDR range of the form x.x.x.x/x"
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1b # same as staging cluster
  InstanceType:
      Description: EC2 instance type
      Type: String
      Default: t3a.small
      AllowedValues:
        - t3a.micro
        - t3a.small
        - t3a.medium
      ConstraintDescription: Must be one of the EC2 instance types allowed by the CloudFormation template

Resources:
  DevServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      # ImageId is: Canonical, Ubuntu, 22.04 LTS, amd64 jammy image build on 2022-09-12
      # - Virtualization: hvm, ENA enabled: true, Root device type: ebs
      # - This ImageId is only available in the us-east-1 region
      # - Image can be used with t3a.nano through t3a.2xlarge (and other types,
      #   but need to consult AWS console for those other types)
      ImageId: ami-08c40ec9ead489470
      AvailabilityZone: !Ref AvailabilityZone
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: slasher-dev
      KeyName: slasher-dev
      SecurityGroupIds:
        - !Ref DevServerSecurityGroup
  DevServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow inbound HTTP/HTTPS/SSH traffic"
      Tags:
        - Key: Name
          Value: slasher-dev
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
  DevServerEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref DevServerInstance
      Tags:
        - Key: Name
          Value: dev-server-eip

Outputs:
  WebsiteURL:
    Value: !Sub http://${DevServerEIP}
    Description: DevServer URL
