/* eslint-disable max-lines */
import React from 'react';

interface Props {
  className?: string;
}

function PrivacyPolicy({ className }: Props) {
  return (
    <div className={className}>
      <h2 className="h3 border-bottom pb-2">Privacy Policy</h2>
      <p>Last updated: May 24, 2019</p>
      <p>
        Premier Audio Video Designs Inc (“us”, “we”, or “our”) operates the
        www.slasher.tv website and the Slasher mobile application (hereinafter
        referred to as the “Service”).
      </p>
      <p>
        This page informs you of our policies regarding the collection, use and
        disclosure of personal data when you use our Service and the choices you
        have associated with that data.
      </p>
      <p>
        We use your data to provide and improve the Service. By using the
        Service, you agree to the collection and use of information in
        accordance with this policy. Unless otherwise defined in this Privacy
        Policy, the terms used in this Privacy Policy have the same meanings as
        in our Terms and Conditions.
      </p>
      <h3 className="h4">Definitions</h3>
      <div className="ms-3">
        <p>
          <strong>Service</strong>
        </p>
        <p>
          Service means the www.slasher.tv website and the Slasher mobile
          application operated by Premier Audio Video Designs Inc
        </p>
        <p>
          <strong>Personal Data</strong>
        </p>
        <p>
          Personal Data means data about a living individual who can be identified
          from those data (or from those and other information either in our
          possession or likely to come into our possession).
        </p>
        <p>
          <strong>Usage Data</strong>
        </p>
        <p>
          Usage Data is data collected automatically either generated by the use
          of the Service or from the Service infrastructure itself (for example,
          the duration of a page visit).
        </p>
        <p>
          <strong>Cookies</strong>
        </p>
        <p>
          Cookies are small files stored on your device (computer or mobile
          device).
        </p>
      </div>
      <h3 className="h4">Information Collection and Use</h3>
      <p>
        We collect several different types of information for various purposes
        to provide and improve our Service to you.
      </p>
      <h3 className="h4">Types of Data Collected</h3>
      <h4 className="h5">Types of Personal Data</h4>
      <p>
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you (“Personal Data”). Personally identifiable information may
        include, but is not limited to:
      </p>
      <ul>
        <li>
          <p>Email address</p>
        </li>
        <li>
          <p>First name and last name</p>
        </li>
        <li>
          <p>Cookies and Usage Data</p>
        </li>
      </ul>
      <p>
        We may use your Personal Data to contact you with newsletters, marketing
        or promotional materials and other information that may be of interest
        to you. You may opt out of receiving any, or all, of these
        communications from us by following the unsubscribe link or the
        instructions provided in any email we send.
      </p>
      <h4 className="h5">Usage Data</h4>
      <p>
        We may also collect information that your browser sends whenever you
        visit our Service or when you access the Service by or through a mobile
        device (“Usage Data”).
      </p>
      <p>
        This Usage Data may include information such as your computer&apos;s Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that you visit, the time and date of your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p>
        When you access the Service with a mobile device, this Usage Data may
        include information such as the type of mobile device you use, your
        mobile device unique ID, the IP address of your mobile device, your
        mobile operating system, the type of mobile Internet browser you use,
        unique device identifiers and other diagnostic data.
      </p>
      <h4 className="h5">Location Data</h4>
      <p>
        We may use and store information about your location if you give us
        permission to do so (“Location Data”). We use this data to provide
        features of our Service, to improve and customise our Service.
      </p>
      <p>
        You can enable or disable location services when you use our Service at
        any time by way of your device settings.
      </p>
      <h4 className="h5">Tracking Cookies Data</h4>
      <p>
        We use cookies and similar tracking technologies to track the activity
        on our Service and we hold certain information.
      </p>
      <p>
        Cookies are files with a small amount of data which may include an
        anonymous unique identifier. Cookies are sent to your browser from a
        website and stored on your device. Other tracking technologies are also
        used such as beacons, tags and scripts to collect and track information
        and to improve and analyse our Service.
      </p>
      <p>
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use some portions of our Service.
      </p>
      <p>Examples of Cookies we use:</p>
      <ul>
        <li>
          <p>
            <strong>Session Cookies.</strong>
            We use Session Cookies to operate our
            Service.
          </p>
        </li>
        <li>
          <p>
            <strong>Preference Cookies.</strong>
            We use Preference Cookies to remember
            your preferences and various settings.
          </p>
        </li>
        <li>
          <p>
            <strong>Security Cookies.</strong>
            We use Security Cookies for security
            purposes.
          </p>
        </li>
        <li>
          <p>
            <strong>Advertising Cookies.</strong>
            Advertising Cookies are used to serve
            you with advertisements that may be relevant to you and your
            interests.
          </p>
        </li>
      </ul>
      <h3 className="h4">Use of Data</h3>
      <p>
        Premier Audio Video Designs Inc uses the collected data for various
        purposes:
      </p>
      <ul>
        <li>
          <p>To provide and maintain our Service</p>
        </li>
        <li>
          <p>To notify you about changes to our Service</p>
        </li>
        <li>
          <p>
            To allow you to participate in interactive features of our Service
            when you choose to do so
          </p>
        </li>
        <li>
          <p>To provide customer support</p>
        </li>
        <li>
          <p>
            To gather analysis or valuable information so that we can improve
            our Service
          </p>
        </li>
        <li>
          <p>To monitor the usage of our Service</p>
        </li>
        <li>
          <p>To detect, prevent and address technical issues</p>
        </li>
        <li>
          <p>
            To provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information
          </p>
        </li>
      </ul>
      <h3 className="h4">Transfer of Data</h3>
      <p>
        Your information, including Personal Data, may be transferred to – and
        maintained on – computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ from those of your jurisdiction.
      </p>
      <p>
        If you are located outside United States and choose to provide
        information to us, please note that we transfer the data, including
        Personal Data, to United States and process it there.
      </p>
      <p>
        Your consent to this Privacy Policy followed by your submission of such
        information represents your agreement to that transfer.
      </p>
      <p>
        Premier Audio Video Designs Inc will take all the steps reasonably
        necessary to ensure that your data is treated securely and in accordance
        with this Privacy Policy and no transfer of your Personal Data will take
        place to an organisation or a country unless there are adequate controls
        in place including the security of your data and other personal
        information.
      </p>
      <h3 className="h4">Disclosure of Data</h3>
      <h4 className="h5">Business Transaction</h4>
      <p>
        If Premier Audio Video Designs Inc is involved in a merger, acquisition
        or asset sale, your Personal Data may be transferred. We will provide
        notice before your Personal Data is transferred and becomes subject to a
        different Privacy Policy.
      </p>
      <h4 className="h5">Disclosure for Law Enforcement</h4>
      <p>
        Under certain circumstances, Premier Audio Video Designs Inc may be
        required to disclose your Personal Data if required to do so by law or
        in response to valid requests by public authorities (e.g. a court or a
        government agency).
      </p>
      <h4 className="h5">Legal Requirements</h4>
      <p>
        Premier Audio Video Designs Inc may disclose your Personal Data in the
        good faith belief that such action is necessary to:
      </p>
      <ul>
        <li>
          <p>To comply with a legal obligation</p>
        </li>
        <li>
          <p>
            To protect and defend the rights or property of Premier Audio Video
            Designs Inc
          </p>
        </li>
        <li>
          <p>
            To prevent or investigate possible wrongdoing in connection with the
            Service
          </p>
        </li>
        <li>
          <p>
            To protect the personal safety of users of the Service or the public
          </p>
        </li>
        <li>
          <p>To protect against legal liability</p>
        </li>
      </ul>
      <h3 className="h4">Security of Data</h3>
      <p>
        The security of your data is important to us but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure. While we strive to use commercially acceptable means to
        protect your Personal Data, we cannot guarantee its absolute security.
      </p>
      <h3 className="h4">Our Policy on “Do Not Track” Signals under the California Online Protection Act (CalOPPA)</h3>
      <p>
        We do not support Do Not Track (“DNT”). Do Not Track is a preference you
        can set in your web browser to inform websites that you do not want to
        be tracked.
      </p>
      <p>
        You can enable or disable Do Not Track by visiting the Preferences or
        Settings page of your web browser.
      </p>
      <h3 className="h4">Service Providers</h3>
      <p>
        We may employ third party companies and individuals to facilitate our
        Service (“Service Providers”), provide the Service on our behalf,
        perform Service-related services or assist us in analysing how our
        Service is used.
      </p>
      <p>
        These third parties have access to your Personal Data only to perform
        these tasks on our behalf and are obligated not to disclose or use it
        for any other purpose.
      </p>
      <h3 className="h4">Analytics</h3>
      <p>
        We may use third-party Service Providers to monitor and analyse the use
        of our Service.
      </p>
      <p>
        <strong>Google Analytics</strong>
      </p>
      <p>
        Google Analytics is a web analytics service offered by Google that
        tracks and reports website traffic. Google uses the data collected to
        track and monitor the use of our Service. This data is shared with other
        Google services. Google may use the collected data to contextualise and
        personalise the ads of its own advertising network.
      </p>
      <p>
        For more information on the privacy practices of Google, please visit
        the Google Privacy Terms web page:
        {' '}
        <a href="https://policies.google.com/privacy?hl=en">
          https://policies.google.com/privacy?hl=en
        </a>
      </p>
      <h3 className="h4">Advertising</h3>
      <p>
        We may use third-party Service Providers to show advertisements to you
        to help support and maintain our Service.
      </p>
      <p>
        <strong>Google AdSense DoubleClick Cookie</strong>
      </p>
      <p>
        Google, as a third party vendor, uses cookies to serve ads on our
        Service. Google&apos;s use of the DoubleClick cookie enables it and its
        partners to serve ads to our users based on their visit to our Service
        or other websites on the Internet.
      </p>
      <p>
        You may opt out of the use of the DoubleClick Cookie for interest-based
        advertising by visiting the Google Ads Settings web page:
        {' '}
        <a href="http://www.google.com/ads/preferences/">
          http://www.google.com/ads/preferences/
        </a>
      </p>
      <p>
        <strong>AdMob by Google</strong>
      </p>
      <p>AdMob by Google is provided by Google Inc.</p>
      <p>
        You can opt-out from the AdMob by Google service by following the
        instructions described by Google:
        {' '}
        <a href="https://support.google.com/ads/answer/2662922?hl=en">
          https://support.google.com/ads/answer/2662922?hl=en
        </a>
      </p>
      <p>
        For more information on how Google uses the collected information,
        please visit the “How Google uses data when you use our partners&apos; sites
        or app” page:
        {' '}
        <a href="http://www.google.com/policies/privacy/partners/">
          http://www.google.com/policies/privacy/partners/
        </a>
        {' '}
        or visit the Privacy Policy of Google:
        {' '}
        <a href="http://www.google.com/policies/privacy/">
          http://www.google.com/policies/privacy/
        </a>
      </p>
      <h3 className="h4">Behavioral Remarketing</h3>
      <p>
        Premier Audio Video Designs Inc uses remarketing services to advertise
        on third party websites to you after you visited our Service. We and our
        third-party vendors use cookies to inform, optimise and serve ads based
        on your past visits to our Service.
      </p>
      <p>
        <strong>Google Ads (AdWords)</strong>
      </p>
      <p>Google Ads (AdWords) remarketing service is provided by Google Inc.</p>
      <p>
        You can opt-out of Google Analytics for Display Advertising and
        customise the Google Display Network ads by visiting the Google Ads
        Settings page:
        {' '}
        <a href="http://www.google.com/settings/ads">
          http://www.google.com/settings/ads
        </a>
      </p>
      <p>
        Google also recommends installing the Google Analytics Opt-out Browser
        Add-on –
        {' '}
        <a href="https://tools.google.com/dlpage/gaoptout">
          https://tools.google.com/dlpage/gaoptout
        </a>
        {' '}
        – for your web browser. Google Analytics Opt-out Browser Add-on provides
        visitors with the ability to prevent their data from being collected and
        used by Google Analytics.
      </p>
      <p>
        For more information on the privacy practices of Google, please visit
        the Google Privacy Terms web page:
        {' '}
        <a href="https://policies.google.com/privacy?hl=en">
          https://policies.google.com/privacy?hl=en
        </a>
      </p>
      <p>
        <strong>Facebook</strong>
      </p>
      <p>Facebook remarketing service is provided by Facebook Inc.</p>
      <p>
        You can learn more about interest-based advertising from Facebook by
        visiting this page:
        {' '}
        <a href="https://www.facebook.com/help/164968693837950">
          https://www.facebook.com/help/164968693837950
        </a>
      </p>
      <p>
        To opt-out from Facebook&apos;s interest-based ads, follow these instructions
        from Facebook:
        {' '}
        <a href="https://www.facebook.com/help/568137493302217">
          https://www.facebook.com/help/568137493302217
        </a>
      </p>
      <p>
        Facebook adheres to the Self-Regulatory Principles for Online
        Behavioural Advertising established by the Digital Advertising Alliance.
        You can also opt-out from Facebook and other participating companies
        through the Digital Advertising Alliance in the USA
        {' '}
        <a href="http://www.aboutads.info/choices/">
          http://www.aboutads.info/choices/
        </a>
        , the Digital Advertising Alliance of Canada in Canada
        {' '}
        <a href="http://youradchoices.ca/">http://youradchoices.ca/</a>
        {' '}
        or the
        European Interactive Digital Advertising Alliance in Europe
        {' '}
        <a href="http://www.youronlinechoices.eu/">
          http://www.youronlinechoices.eu/
        </a>
        , or opt-out using your mobile device settings.
      </p>
      <p>
        For more information on the privacy practices of Facebook, please visit
        Facebook&apos;s Data Policy:
        {' '}
        <a href="https://www.facebook.com/privacy/explanation">
          https://www.facebook.com/privacy/explanation
        </a>
      </p>
      <h3 className="h4">Payments</h3>
      <p>
        We may provide paid products and/or services within the Service. In that
        case, we use third-party services for payment processing (e.g. payment
        processors).
      </p>
      <p>
        We will not store or collect your payment card details. That information
        is provided directly to our third-party payment processors whose use of
        your personal information is governed by their Privacy Policy. These
        payment processors adhere to the standards set by PCI-DSS as managed by
        the PCI Security Standards Council, which is a joint effort of brands
        like Visa, MasterCard, American Express and Discover. PCI-DSS
        requirements help ensure the secure handling of payment information.
      </p>
      <p>The payment processors we work with are:</p>
      <p>
        <strong>Apple Store In-App Payments</strong>
      </p>
      <p>
        Their Privacy Policy can be viewed at
        {' '}
        <a href="https://www.apple.com/legal/privacy/en-ww/">
          https://www.apple.com/legal/privacy/en-ww/
        </a>
      </p>
      <p>
        <strong>Google Play In-App Payments</strong>
      </p>
      <p>
        Their Privacy Policy can be viewed at
        {' '}
        <a href="https://www.google.com/policies/privacy/">
          https://www.google.com/policies/privacy/
        </a>
      </p>
      <p>
        <strong>PayPal / Braintree</strong>
      </p>
      <p>
        Their Privacy Policy can be viewed at
        {' '}
        <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full">
          https://www.paypal.com/webapps/mpp/ua/privacy-full
        </a>
      </p>
      <h3 className="h4">Links to Other Sites</h3>
      <p>
        Our Service may contain links to other sites that are not operated by
        us. If you click a third party link, you will be directed to that third
        party&apos;s site. We strongly advise you to review the Privacy Policy of
        every site you visit.
      </p>
      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      <h3 className="h4">Children&apos;s Privacy</h3>
      <p>
        Our Service does not address anyone under the age of 18 (“Children”).
      </p>
      <p>
        We do not knowingly collect personally identifiable information from
        anyone under the age of 18. If you are a parent or guardian and you are
        aware that your Child has provided us with Personal Data, please contact
        us. If we become aware that we have collected Personal Data from
        children without verification of parental consent, we take steps to
        remove that information from our servers.
      </p>
      <h3 className="h4">Changes to This Privacy Policy</h3>
      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        We will let you know via email and/or a prominent notice on our Service,
        prior to the change becoming effective and update the “effective date”
        at the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <h3 className="h4">Contact Us</h3>
      <p>
        If you have any questions about this Privacy Policy, please contact us:
      </p>
      <ul>
        <li>
          <p>
            By email: help@slasher.tv
          </p>
        </li>
      </ul>
    </div>
  );
}

PrivacyPolicy.defaultProps = {
  className: '',
};

export default PrivacyPolicy;
