AWSTemplateFormatVersion: 2010-09-09
Description: Sets Up API and Cron Services
Parameters:
  BuildNumber:
    Type: String
    Default: latest

  ClusterName:
    Default: slasher
    Type: String

  Stage:
    Default: staging
    Type: String

  TypeProject:
    Default: server_v2
    Type: String

  BackendSiteDomain:
    Default: stagingapi-v2.slasher.tv
    Type: String

  FrontendSiteDomain:
    Type: String
    Default: app-staging.slasher.tv

  NginxPort:
    Default: 80
    Type: Number

  AppPort:
    Default: 4000
    Type: Number

  AppVirtualCPUs:
    Default: 128
    Type: Number

  AppMemoryMin:
    Default: 128
    Type: Number

  AppMemoryMax:
    Type: String
    Default: 'LIMITLESS'

  CronVirtualCPUs:
    Default: 128
    Type: Number

  CronMemoryMin:
    Default: 128
    Type: Number

  CronMemoryMax:
    Type: String
    Default: 'LIMITLESS'

  NginxVirtualCPUs:
    Default: 128
    Type: Number

  NginxMemoryMin:
    Default: 128
    Type: Number

  NginxMemoryMax:
    Type: String
    Default: 'LIMITLESS'

Conditions:
  hasOnlyOneTask: !Equals [!Ref EcsTasksNumber, "1"]
  appHasMemoryLimit: !Not [!Equals [!Ref AppMemoryMax, "LIMITLESS"]]
  cronHasMemoryLimit: !Not [!Equals [!Ref CronMemoryMax, "LIMITLESS"]]
  nginxHasMemoryLimit: !Not [!Equals [!Ref NginxMemoryMax, "LIMITLESS"]]
