AWSTemplateFormatVersion: 2010-09-09
Description: Sets Up Service Elb
Parameters:
  ClusterName:
    Type: String

  Stage:
    Type: String

  TypeProject:
    Type: String

  NginxPort:
    Type: Number
    Default: 80

  DefaultAcmCertificateArn:
    Type: String

  BackendSiteDomain:
    Type: String
