# Docker compose setup for development and testing
version: "3.9"

# Although a name isn't required for docker to work, we want to explicitly specify it so we know
# which prefix is used for the volumes that we create.
name: 'slasher-devtest'

volumes:
  mongo-data:
services:
  mongo:
    build: ../docker/mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      # As a convenience, set an environment variable in the container with the connection URL
      - MONGODB_ROOT_CONNECTION_URL='mongodb://root:rootpassword@localhost:27017/example?authSource=admin'
