import postImage from '../../images/book-post-image.jpg';

export const homePost = [
  {
    _id: 'post01',
    id: 'post01',
    postDate: '2022-06-18T17:40:12.000Z',
    contentHeading: 'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.',
    content: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
    userName: 'Maureen Biologist',
    profileImage: 'https://i.pravatar.cc/300?img=14',
    userId: 'user01',
    likes: 20,
    likeIcon: false,
    likeCount: 20,
    commentCount: 10,
    postedIn: 'Black Horror World',
    type: 'Movie review',
  },
  {
    _id: 'post02',
    id: 'post02',
    postDate: '2022-06-18T17:40:12.000Z',
    contentHeading: 'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.',
    content: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
    userName: 'Maureen Biologist',
    profileImage: 'https://i.pravatar.cc/300?img=12',
    userId: 'user01',
    images: [{ image_path: postImage, _id: 'postImag01' }],
    likes: 20,
    likeIcon: false,
    likeCount: 20,
    commentCount: 10,
    postedIn: 'Blogs & Vlogs',
    type: 'Discussion',
  },
  {
    _id: 'post03',
    id: 'post03',
    postDate: '2022-06-18T17:40:12.000Z',
    contentHeading: 'There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.',
    content: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
    userName: 'Maureen Biologist',
    profileImage: 'https://i.pravatar.cc/300?img=14',
    userId: 'user01',
    likes: 20,
    likeIcon: false,
    likeCount: 20,
    commentCount: 10,
    postedIn: 'Slasher news & updates',
    type: 'Movie review',
  },
];

export const listAll = [
  {
    _id: 'list01',
    contentHeading: 'Slasher feedback & feature requests',
    content: 'How can we make Slasher better for you?',
    ljGroup: false,
    pinned: true,
  },
  {
    _id: 'list02',
    contentHeading: 'Slasher frequently asked questions',
    content: 'Get answers to common questions here',
    ljGroup: false,
    pinned: true,
  },
  {
    _id: 'list03',
    contentHeading: 'Slasher news & updates',
    content: 'The latest on new features and app updates',
    ljGroup: true,
    pinned: true,
  },
  {
    _id: 'list04',
    contentHeading: 'Art',
    content: 'Horror art & artists',
    ljGroup: true,
    pinned: false,
  },
  {
    _id: 'list05',
    contentHeading: 'Black Horror World',
    content: 'Horror in the world of black cinema',
    ljGroup: false,
    pinned: false,
  },
  {
    _id: 'list06',
    contentHeading: 'Blogs & Vlogs',
    content: 'Share your favorite horror blogs &  vlogs',
    ljGroup: true,
    pinned: false,
  },
];
